### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by edgarasben** [tailwindlabs/tailwindcss-jit#168]
### What version of @tailwindcss/jit are you using?

v0.1.11 → (Updated: v0.1.12)

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/edgarasben/bulletproof-ui/blob/main/src/Button.jsx

I get an error only when I switch to `'@tailwindcss/jit'` PostCSS plugin and I am trying to build a conditional CSS classes with React + Vite.

The error occurs when I add this to the Button.jsx file:

```
  const types = {
    primary: 'bg-blue-600 hover:bg-blue-700 text-white',
    secondary:
      'bg-blue-700 text-blue-600 hover:bg-blue-700 bg-opacity-20 hover:bg-opacity-30',
  }
  const whichType = types[props.buttonType]
```

Error log
```
[plugin:vite:css] Maximum call stack size exceeded
/Users/edgaras/Documents/Sites/bulletproof-ui/src/index.css
    at candidatePermutations (/Users/edgaras/Documents/Sites/bulletproof-ui/node_modules/@tailwindcss/jit/src/lib/generateRules.js:19:32)
    at candidatePermutations (/Users/edgaras/Documents/Sites/bulletproof-ui/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/edgaras/Documents/Sites/bulletproof-ui/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/edgaras/Documents/Sites/bulletproof-ui/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/edgaras/Documents/Sites/bulletproof-ui/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/edgaras/Documents/Sites/bulletproof-ui/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10
```

**Comment by edgarasben** [comment]
Updated JIT to 0.1.12. Getting the same issue.

**Comment by u12206050** [comment]
Getting a very similar issue but seems tied to postcss-loader:

```Module build failed (from ./node_modules/gridsome/node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:19:32)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (/Users/gl/Sites/africa/node_modules/@tailwindcss/jit/src/lib/generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
```

**Comment by adamwathan** [comment]
Fixed in v0.1.13, sorry about that!

**Comment by edgarasben** [comment]
Works great now! Thank you. 🙏

**Comment by prbroadfoot** [comment]
> Fixed in v0.1.13, sorry about that!

I am still getting "Maximum call stack size exceeded" error in v0.1.13 (v0.1.11 works)

**Comment by adamwathan** [comment]
@prbroadfoot Can you provide a reproduction? What input is triggering the overflow?

**Comment by prbroadfoot** [comment]
@adamwathan 

I have purge watching a directory of JS files compiled from ClojureScript. Here is one of the files that triggers it:

https://gist.github.com/prbroadfoot/e4eee9a106fa6f551e9ba2c5d1827876

**Comment by adamwathan** [comment]
@prbroadfoot I just tried running against that file locally and had no issues. Any chance you can create a GitHub repo I can clone that reproduces please? In a new issue would be ideal so I don't lose track of it 👍🏻
